name: my_image_picker
description: A Flutter package to pick images with custom design
version: 0.0.1
homepage: "https://github.com/rizalahmaddd/my_image_picker"

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jagodev.my_image_picker
        pluginClass: MyImagePickerPlugin